version: '3.8'

services:

  redis:
    image: redis
    restart: always
    command: --requirepass "123456" --maxclients 100
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis_data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "1"