/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TryJson;

import org.json.JSONObject;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws IOException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        // 默认使用UTF-8编码读取:
        byte[] content = Files.readAllBytes(Paths.get("json-content.json"));
        JSONObject jo = new JSONObject(new String(content));
        assertEquals("123", jo.get("a"));
        assertEquals("org.json.JSONObject", jo.get("c").getClass().getName());
        assertEquals("org.json.JSONArray", jo.get("d").getClass().getName());
        assertEquals("org.json.JSONObject", jo.get("e").getClass().getName());
        assertEquals("org.json.JSONArray", jo.get("f").getClass().getName());
        assertEquals("java.lang.String", jo.get("g").getClass().getName());
        assertEquals("java.lang.Boolean", jo.get("h").getClass().getName());
    }
}
