/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TryJson;

import org.json.JSONObject;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        JSONObject jo = new JSONObject("""
                {
                    "a": "123",
                    "b": "456",
                    "c": {"a": "1", "b": "2"},
                    "d": [
                        {"a": "1", "b": "2"},
                        {"a": "1", "b": "2"},
                        {"a": "1", "b": "2"}
                    ],
                    "e": {},
                    "f": [],
                    "g": "01ww",
                    "h": true
                }
                """);
        assertEquals("123", jo.get("a"));
        assertEquals("org.json.JSONObject", jo.get("c").getClass().getName());
        assertEquals("org.json.JSONArray", jo.get("d").getClass().getName());
        assertEquals("org.json.JSONObject", jo.get("e").getClass().getName());
        assertEquals("org.json.JSONArray", jo.get("f").getClass().getName());
        assertEquals("java.lang.String", jo.get("g").getClass().getName());
        assertEquals("java.lang.Boolean", jo.get("h").getClass().getName());
    }
}
