version: '3.1'

services:
  tomcat:
    restart: always
    image: tomcat:jdk15-adoptopenjdk-openj9
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - ./ServletJSP/target/ServletJSP-1.0:/usr/local/tomcat/webapps/ROOT
    environment:
      TZ: Asia/Shanghai

  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql:delegated"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome1:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - START_XVFB=false