version: '3.8'

services:

  hive:
    build: cluster
    ports:
      - "10000:10000"
    volumes:
      - "./slaves:/hadoop/etc/hadoop/slaves"
      - "./data/hive/meta:/home/hive/meta"
    entrypoint:
      - /hive/start_hive.sh

  name-node:
    build: cluster
    ports:
      - "9000:9000"
      - "50070:50070"
    volumes:
      - "./slaves:/hadoop/etc/hadoop/slaves"
      - "./data/dfs/name:/home/hdfs/dfs"
    entrypoint:
      - /hadoop/start_namenode.sh

  resource-manager:
    build: cluster
    ports:
      - "8088:8088"
      - "19888:19888"
    volumes:
      - "./slaves:/hadoop/etc/hadoop/slaves"
    entrypoint:
      - /hadoop/start_resource_manager.sh

  data-node1:
    build: cluster
    volumes:
      - "./slaves:/hadoop/etc/hadoop/slaves"
      - "./data/dfs/node1:/home/hdfs/dfs"
    entrypoint:
      - /hadoop/start_datanode.sh

  data-node2:
    build: cluster
    volumes:
      - "./slaves:/hadoop/etc/hadoop/slaves"
      - "./data/dfs/node2:/home/hdfs/dfs"
    entrypoint:
      - /hadoop/start_datanode.sh