version: '3.1'

services:
  tomcat:
    restart: always
    image: tomcat:jdk15-adoptopenjdk-openj9
    container_name: tomcat
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/tomcat/webapps/ROOT
    environment:
      TZ: Asia/Shanghai