### Authorization Code + PKCE (login in browser first so JSESSIONID is set)
# Spring Authorization Server 7 defaults require-proof-key=true
< {%
    const verifier = "6lZU94u62DfIzqePlE0GX7EvcA-3qD-EXLsgh67EtXwtKJNHLsnO2lH3JTVPKAtC";
    request.variables.set("codeVerifier", verifier);
    const challenge = crypto.sha256()
        .updateWithText(verifier)
        .digest()
        .toBase64(true)   // urlSafe
        .replace(/=+$/, ""); // PKCE: strip padding
    request.variables.set("codeChallenge", challenge);
%}
GET {{baseUrl}}/oauth2/authorize
    ?response_type=code
    &client_id={{clientId}}
    &redirect_uri={{redirectUri}}
    &scope=openid
    &code_challenge={{codeChallenge}}
    &code_challenge_method=S256

> {%
  const actionMatch = response.body.match(/method="post"\s+action="([^"]+)"/);
  console.log(actionMatch[1])
  const m = response.body.match(/name="_csrf"\s+type="hidden"\s+value="([^"]+)"/);
  console.log(m[1])
  client.global.set("loginUrl", actionMatch[1]);
  client.global.set("_csrf", m[1]);
  console.log(response.headers)
%}

### Login (POST to loginUrl with username, password, and _csrf)
# @no-redirect
POST {{baseUrl}}{{loginUrl}}
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}&_csrf={{_csrf}}

> {%
    console.log(response.headers)
    const location = response.headers.valueOf("Location");
    client.global.set("authorizationUrl", location);
%}

### Loged in, follow redirect to get authorization code (code=)
# @no-redirect
GET {{authorizationUrl}}

> {%
    console.log(response.headers)
    const location = response.headers.valueOf("Location");
    const m = location.match(/code=([^&]+)/);
    console.log(m)
    client.global.set("authorizationCode", m[1]);
%}


### Token exchange (paste authorization code into code=)
# Authorization: Basic base64(oidc-client:secret)
< {%
    const base64ClientIdSecret = `${request.environment.get("clientId")}:${request.environment.get("clientSecret")}`;
    client.global.set("base64ClientIdSecret", base64ClientIdSecret);
%}
POST {{baseUrl}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientId}} {{clientSecret}}

grant_type=authorization_code&code={{authorizationCode}}&redirect_uri={{redirectUri}}&code_verifier={{codeVerifier}}&scope=openid

###
