services:
  gateway:
    hostname: gateway
    image: eclipse-temurin:26-jdk
    ports:
      - "80:8080"
    depends_on:
      - authorization-server

  resource-server:
    hostname: resource-server
    image: eclipse-temurin:26-jdk
#    ports:
#      - "8090:8090"
    depends_on:
      - authorization-server

  oauth2-login:
    hostname: oauth2-login
    image: eclipse-temurin:26-jdk
#    ports:
#      - "8090:8090"
    depends_on:
      - authorization-server

  nacos-server:
    hostname: nacos-server
    image: nacos/nacos-server:v3.2.3
#    ports:
#      - "8848:8848"
#      - "8088:8080"
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
    # After first start, init console admin once:
    # curl -X POST 'http://127.0.0.1:8088/v3/auth/user/admin' -d 'password=nacos'

  authorization-server:
    hostname: authorization-server
    image: eclipse-temurin:26-jdk
#    ports:
#      - "8080:8080"
    depends_on:
      - authorization-server-db
      - nacos-server

  authorization-server-db:
    hostname: authorization-server-db
    image: mysql:9.7
#    ports:
#      - "3306:3306"
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: oauth2
