spring:
  application:
    name: resource-server
  cloud:
    nacos:
      username: nacos
      password: 123
      discovery:
        server-addr: nacos-server:8848
        fail-fast: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:8080
server:
  port: 8092