###
http://localhost:8080/oauth/authorize?client_id=c1&client_secret=123&response_type=code&redirect_uri=https://www.baidu.com

###
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&client_id=c1&client_secret=123&redirect_uri=https://www.baidu.com&code=sm2a2Z

###
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=c1&client_secret=123&username=user&password=123
