version: '3.1'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql:delegated"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_flush_log_at_trx_commit=0 --max_connections=10000
    #command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test