version: '3.1'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql:delegated"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test