spring:
  application:
    name: authorization-server
  sql:
    init:
      mode: always
  cloud:
    nacos:
      username: nacos
      password: 123
      discovery:
        server-addr: nacos-server:8848
        fail-fast: true
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: AUTHORIZATION_SERVER_SESSION
app:
  datasource:
    url: jdbc:mysql://authorization-server-db/oauth2?preserveInstants=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
    username: root
    password: 123
    pool-size: 30
  sms:
    codes:
      "13800000000": "123456"
