### user:password
http://localhost:8080
Authorization: Basic dXNlcjpwYXNzd29yZA==

### admin:password
http://localhost:8080
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### fake credential
http://localhost:8080
Authorization: Basic aaaaaaaaa