version: '3.8'

services:

  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql:delegated"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test