version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "./data:/bitnami/zookeeper"
    restart: always
    user: root
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes